command:
- "python"
- "app.py"

env:
- name: "SPACE_ID"
  value: "01f0663affb21e319dd62d0c67d89cf8"
- name: "POWERBI_EMBED_URL"
  value: "https://app.powerbi.com/reportEmbed?reportId=25baf2c4-2cc6-434d-94c1-157650590c23&autoAuth=true&ctid=9f37a392-f0ae-4280-9796-f1864a10effc"